.TH ORPHAN\-THUMBNAIL 1 "October 2009" "orphan-thumbnail 0.0.2" "User Manual"
.SH NAME
orphan-thumbnail \- A program to find orphan GNOME thumbnail
.SH SYNOPSIS
.B orphan\-thumbnail
[\fIOPTION\fR] ...
.SH DESCRIPTION
.B orphan-thumbnail
is a program to find orphan GNOME thumbnails. It reads thumbnails and 
looks for the URI to the original file in PNG comments. It is capable 
to show and/or delete orphan thumbnails.
.SH OPTIONS
.IP \fB\-d\fR,\ \fB\-\-delete\fR
delete orphan thumbnail(s)
.IP \fB\-o\fR,\ \fB\-\-orphan\fR
list only orphan thumbnail(s)
.IP \fB\-q\fR,\ \fB\-\-quiet\fR
Quiet mode, only if \fB-d\fR is specified
.IP \fB\-v\fR,\ \fB\-\-version\fR
Print version
.IP \fB\-h\fR,\ \fB\-\-help\fR
Print help page
.SH BUGS
are probably there
.SH AUTHOR
orphan-thumbnail is written by Kitt Tientanopajai
.SH "REPORTING BUGS"
Report bugs to <kitty@kitty.in.th>
.br
orphan-thumbnail home page: <http://kitty.in.th/index.php?page=orphan-thumbnail>
.SH COPYRIGHT
Copyright \(co 2009 Kitt Tientanopajai.
License: GNU GPL version 2 or later.
.br
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
